version: '2'
services:
  doc-db:
    build: './doc-db/'
    container_name: 'doc-db'
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: doc
    ports:
      - "13306:3306"